apiVersion: v2
name: grafana
description: NKE Grafana
type: application
version: 2.5.0
appVersion: "2.5.0"

dependencies:
  - name: grafana
    version: 6.40.1
    repository: https://grafana.github.io/helm-charts
