grafana:
  adminPassword: "nutanix/4u"
  ingress:
    enabled: true
    hosts:
      - grafana.labo.nxlab.fr
    annotations:
      kubernetes.io/ingress.class: nginx

  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus-k8s
          type: prometheus
          access: proxy
          url: http://prometheus-k8s.ntnx-system:9090
          isDefault: true

  persistence:
    type: pvc
    enabled: false
