apiVersion: v2
name: cert-manager
description: NKE cert-manager
type: application
version: 1.0.0
appVersion: "v1.9.1"

dependencies:
  - name: cert-manager
    version: 1.9.1
    repository: https://charts.jetstack.io
